env_config: environments/configs/template_eval_acceleration_delay_free.yaml
policy_config: baselines/configs/cpid_acceleration.yaml

runner:
  target_episodes: 500
  max_steps: null
  render: false
  save_rollout: true

logging:
  root_dir: logs/cpid_acceleration_500
  run_name: cpid_target_position_acceleration_delay_free
