policy_name: cpid_acceleration

angle_pid:
  kp: 0.5
  ti: 1.5
  td: 0.6
  max_theta_change: 0.014
  max_theta_ref: 0.03

acceleration_pid:
  kp: 10.0
  ti: 1000.0
  td: 0.0
  max_delta_acc: auto
  max_acc: auto
  action_sign: -1.0
