env_config: environments/configs/template_eval_acceleration_delay_free.yaml
policy_config: baselines/configs/rl_rpo_error10.yaml
checkpoint_path: null

runner:
  target_episodes: 500
  max_steps: null
  render: false
  save_rollout: true

logging:
  root_dir: logs/rl_train/rpo_target_position_acceleration_error10_seed_2025/acceleration_delay_free_error10
  run_name: rpo_target_position_acceleration_error10_eval_delay_4_disturbance
