env_config: environments/configs/unified_tracking_mixed.yaml
policy_config: baselines/configs/rl_rpo_relative_reference_preview_train.yaml

seed: 2025

training:
  max_iterations: 300
  rollouts: auto
  batch_size: 512
  learning_epochs: 4
  mini_batches: auto
  random_timesteps: 0
  learning_starts: 0
  rpo_alpha: 0.5
  write_interval: 10
  checkpoint_interval: null
  wandb: true
  wandb_kwargs:
    project: unified_tracking

logging:
  root_dir: logs/rl_unified_tracking
  run_name: rpo_unified_tracking_relative_reference_preview_train
