task_name: unified_tracking
interface_name: velocity

env:
  seed: 666
  num_envs: 10
  episode_length_s: 20.0
  device: cuda:0

unified_tracking_task:
  trajectory_types: [constant]
  trajectory_type_weights: [1.0]
  constant_goal_range: [0.10, 0.60]
  dynamic_center_range: [0.3, 0.4]
  amplitude_range: [0.10, 0.25]
  period_range: [4.0, 10.0]
  phase_range: [0.0, 0.0]
  constant_initialization_mode: independent_uniform
  dynamic_initialization_mode: on_reference
  fixed_initial_ball_position: 0.35
  initial_ball_position_range: [0.10, 0.60]
  min_initial_reference_distance: 0.05
  position_weight: 5.0
  velocity_weight: 0.5
  command_weight: 0.5
  action_weight: 1.0
  failure_penalty: 500.0
  progress_weight: 1.0
  max_error_for_failure: 0.5

reference_preview:
  enabled: true
  future_steps: 30

velocity_interface:
  max_acc: 5.0
  max_velocity: 0.0

robustness:
  enabled: true
  ball_mass_variation_enabled: false
  ball_mass_range: [0.0005, 0.0005]
  recompute_ball_inertia: true
  controller_gain_variation_enabled: false
  controller_gain_range: [10.0, 10.0]
  action_delay_enabled: false
  delay_step: 8
  velocity_response_enabled: true
  velocity_response_tau_s_range: [0.150, 0.160]
  velocity_response_gain_range: [0.84, 0.88]
  velocity_response_bias_range: [-0.004, -0.003]
  # velocity_response_tau_s_range: [0.0, 0.0]
  # velocity_response_gain_range: [1.0, 1.0]
  # velocity_response_bias_range: [0.0, 0.0]
  velocity_response_noise_mode: none
  velocity_response_noise_std_range: [0.02, 0.05]
  velocity_response_ou_theta_range: [4.0, 10.0]
  velocity_response_ou_mu_range: [0.0, 0.0]
  velocity_response_noise_clip: 0.1
  velocity_response_max_abs_velocity: 0.0
  velocity_response_sim_tau_s: 0.1000
  velocity_response_sim_gain: 1.0127
  velocity_response_sim_bias: -0.000564
  velocity_response_sim_max_abs_velocity: 0.0
  external_disturbance_enabled: false
  external_disturbance_ou_mu: 0.0
  external_disturbance_ou_theta_range: [0.1, 0.3]
  external_disturbance_ou_sigma_range: [0.01, 0.05]
  external_disturbance_ou_clip: 0.05

unified_tracking_evaluator:
  num_eval_episodes: 1000
  target_zone: 0.01
  steady_state_window_s: 1.0

runner:
  target_episodes: 1000
  max_steps: null
  render: false
  save_rollout: true

logging:
  root_dir: logs/zero_action/unified_tracking
  run_name: zero_action_unified_tracking_constant
